name: llm-operators
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=21.4.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.07.19
  - cairo=1.16.0
  - certifi=2022.9.14
  - ffmpeg=4.3.2
  - fontconfig=2.13.94
  - freetype=2.10.4
  - gettext=0.19.8.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - graphite2=1.3.13
  - harfbuzz=2.9.1
  - hdf5=1.12.1
  - icu=68.2
  - iniconfig=1.1.1
  - jasper=1.900.1
  - jbig=2.1
  - jpeg=9e
  - krb5=1.19.2
  - lame=3.100
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.79.1
  - libcxx=12.0.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.68.4
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.20
  - libopencv=4.5.3
  - libpng=1.6.37
  - libprotobuf=3.16.0
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp-base=1.2.2
  - libxml2=2.9.12
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - ncurses=6.3
  - nettle=3.6
  - numpy=1.22.2
  - opencv=4.5.3
  - openh264=2.1.1
  - openssl=1.1.1q
  - packaging=21.3
  - pcre=8.45
  - pip=21.2.4
  - pixman=0.40.0
  - pluggy=1.0.0
  - py=1.11.0
  - py-opencv=4.5.3
  - pyparsing=3.0.9
  - pytest=7.1.2
  - python=3.9.12
  - python_abi=3.9
  - readline=8.1.2
  - setuptools=61.2.0
  - sqlite=3.38.3
  - tk=8.6.12
  - tomli=2.0.1
  - tzdata=2022a
  - wheel=0.37.1
  - x264=1!161.3030
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.0
  - pip:
    - antlr4-python3-runtime=
    - charset-normalizer=
    - cloudpickle=
    - cycler=
    - et-xmlfile=
    - fonttools=
    - gym=
    - gym-notices=
    - idna=
    - imageio=
    - importlib-metadata=
    - kiwisolver=
    - matplotlib=
    - networkx=
    - openai=
    - openpyxl=
    - pandas=
    - pandas-stubs=
    - pddlgym=
    - pddlpy=
    - pillow=
    - python-dateutil=
    - pytz=
    - pywavelets=
    - requests=
    - scikit-image=
    - scipy=
    - six=
    - tifffile=
    - tqdm=
    - urllib3=
    - zipp=
